# Generated by Django 3.1.4 on 2020-12-01 19:46

import os

from django.db import migrations
from django.conf import settings

from django.contrib.auth.hashers import make_password


def create_default_superuser(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # User = apps.get_model(settings.AUTH_USER_MODEL)

    superuser = User.objects.create(
        username='admin',
        password=make_password(os.getenv('ADMIN_PASSWORD', 'qweqweqwe')),
        is_superuser=True,
        is_staff=True
    )
    superuser.save()

    # superuser = User.objects.create_superuser(
    #     username='admin',
    #     email='admin@admin.com',
    #     password=os.getenv('ADMIN_PASSWORD', 'qweqweqwe')
    # )
    # superuser.save()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_superuser),
    ]
